grails-app/domain/officeolympics/Medals.groovy
package officeolympics

class Medals {
	String level
	String sportName
	static belongsTo = [teams: Team]
	static constraints = { teams nullable: true }
}

grails-app/domain/officeolympics/Team.groovy
package officeolympics

class Team {
	
		String teamName
		Integer score
		static hasMany = [members: TeamMembers, medals: Medals]
		
   
   
}

grails-app/controllers/officeolympics/TeamController.groovy
package officeolympics



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class TeamController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Team.list(params), model:[teamInstanceCount: Team.count()]
    }

    def show(Team teamInstance) {
        respond teamInstance
    }

    def create() {
        respond new Team(params)
    }

    @Transactional
    def save(Team teamInstance) {
        if (teamInstance == null) {
            notFound()
            return
        }

        if (teamInstance.hasErrors()) {
            respond teamInstance.errors, view:'create'
            return
        }

        teamInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'team.label', default: 'Team'), teamInstance.id])
                redirect teamInstance
            }
            '*' { respond teamInstance, [status: CREATED] }
        }
    }

    def edit(Team teamInstance) {
        respond teamInstance
    }

    @Transactional
    def update(Team teamInstance) {
        if (teamInstance == null) {
            notFound()
            return
        }

        if (teamInstance.hasErrors()) {
            respond teamInstance.errors, view:'edit'
            return
        }

        teamInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Team.label', default: 'Team'), teamInstance.id])
                redirect teamInstance
            }
            '*'{ respond teamInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Team teamInstance) {

        if (teamInstance == null) {
            notFound()
            return
        }

        teamInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Team.label', default: 'Team'), teamInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'team.label', default: 'Team'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/team/_form.gsp
<%@ page import="officeolympics.Team" %>



<div class="fieldcontain ${hasErrors(bean: teamInstance, field: 'members', 'error')} ">
	<label for="members">
		<g:message code="team.members.label" default="Members" />
		
	</label>
	
<ul class="one-to-many">
<g:each in="${teamInstance?.members?}" var="m">
    <li><g:link controller="teamMembers" action="show" id="${m.id}">${m?.playerName.encodeAsHTML()}</g:link></li>
</g:each>
<li class="add">
<g:link controller="teamMembers" action="create" params="['team.id': teamInstance?.id]">${message(code: 'default.add.label', args: [message(code: 'teamMembers.label', default: 'TeamMembers')])}</g:link>
</li>
</ul>


</div>

<div class="fieldcontain ${hasErrors(bean: teamInstance, field: 'score', 'error')} required">
	<label for="score">
		<g:message code="team.score.label" default="Score" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="score" type="number" value="${teamInstance.score}" required=""/>

</div>

<div class="fieldcontain ${hasErrors(bean: teamInstance, field: 'teamName', 'error')} required">
	<label for="teamName">
		<g:message code="team.teamName.label" default="Team Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="teamName" required="" value="${teamInstance?.teamName}"/>

</div>

grails-app/views/team/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'team.label', default: 'Team')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-team" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-team" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${teamInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${teamInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:teamInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/team/current.gsp
<html>
	<head>
		<title>Current Projects</title>
	</head>

<body>
<table border="1">
<g:each in="${allProjects}" status = "i" var = "thisProject">
<tr>
<td>${thisProject.name}</td>
<td>${thisProject.description}</td>
<td>${thisProject.dueDate}</td>
</tr>
</g:each>
</table>

</body>
</html>

grails-app/views/team/edit.gsp
<%@ page import="officeolympics.Team" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'team.label', default: 'Team')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-team" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-team" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${teamInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${teamInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:teamInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${teamInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/team/index.gsp
<%@ page import="officeolympics.*" %>

<!DOCTYPE html>
<html lang="en">
<head>
	<g:set var="entityName" value="${message(code: 'medals.label', default: 'Medals')}" />
	<title>Office Olympics</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
 
	<style>
		table{
			width:75%
		}
		table,th, td {
			border: 1px solid black;
			border-collapse: collapse;
		}
		th, td {
			padding: 5px
		}
		td {
			text-align: left;
		}
		table#t01 tr:nth-child(even) {
			background-color: #eee;
		}
		table#t01 tr:nth-child(odd) {
			background-color:#fff;
		}
		table#t01 th	{
			background-color: black;
			color: white;
		}
	</style>
</head>

<body>
<!--Navigation Bar-->
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
			<a class="navbar-brand" href="#">Office Olympics</a>
		</div>
		<div>
			<ul class="nav navbar-nav">
				<li class ="active"><a href="${createLink(uri: '/')}">Home</a></li>
				<li><g:link controller="medals" class="create" action="create">New Game Result</g:link></li>
			</ul>
		</div>
	</div>
</nav>

<br>
<br>

<!--Score, Team Name, and List of Team Members-->
<div class="container" height="500">        
  <table class="table table-striped">
	<thead>
		<tr>
			<g:sortableColumn property="score" title="${message(code: 'team.score.label', default: 'Score')}" />
			<th>Team Name</th>
			<th>Team Members</th>
		</tr>
    </thead>
    <tbody>
		<g:each in="${teamInstanceList}" status="i" var="team">
		<tr>
			<td><h2><g:link action="show" id="${team.id}">${fieldValue(bean: team, field: "score")}</g:link></h2></td>
			<td><h3>${team.teamName}</h3></td>
			<!--This loops through the Team Members names to get all of the names in list form-->
			<td>
				<ul>
					<g:each var="player" in="${team.members}">
						<li>${player.playerName}</li>
					</g:each>
				<ul>
			</td>
		</tr>
		</g:each>
	</tbody>
  </table>
</div>

<br>
<br>
	
<!--This tables lists out the medals that each team has won-->	
<div class="container" height="500">
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Team Name</th>
				<th>Medals</th>
			</tr>
		</thead>
		<tbody>
			<g:each in="${teamInstanceList}" status="i" var="team">
			<tr>
				<td><h3>${team.teamName}</h3></td>
				<td>
					<ul>
					<g:each var="medal" in="${team.medals}">
						 <li>${medal.level} in ${medal.sportName}</li>
					</g:each>
					</ul>
				</td>
			</tr>
			</g:each>
		</tbody>
	</table>
</div>

<br>
<br>

<!--Form to submit an new medal-->
<g:form controller="result" action="save">

<div>
	<label for="sportName">
		<g:message code="medals.sportName.label" default="Sport Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="sportName" required="" value="${medalsInstance?.sportName}"/>

</div>
<table><tbody>
<tr>
<td>
<div>
	<label for="Gold">
	<g:message code="medals.teams.label" default="Gold" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="gold" name="goldWinner" from="${officeolympics.Team.list()}" required="" optionKey="id" optionValue="teamName" value="${medalsInstance?.teams?.id}" class="many-to-one" noSelection="['null': '']"/>

</div>
</td><td>
<div>
	<label for="Silver">
	<g:message code="medals.teams.label" default="Silver" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="silver" name="silverWinner" from="${officeolympics.Team.list()}" required="" optionKey="id" optionValue="teamName" value="${medalsInstance?.teams?.id}" class="many-to-one" noSelection="['null': '']"/>

</div>
</td><td>
<div>
	<label for="Bronze">
	<g:message code="medals.teams.label" default="Bronze" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="bronze" name="bronzeWinner" from="${officeolympics.Team.list()}"  required="" optionKey="id" optionValue="teamName" value="${medalsInstance?.teams?.id}" class="many-to-one" noSelection="['null': '']"/>

</div>
</td></tr></tbody></table>




<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
</g:form>





>>>>>>> OneSubmitButton
<h2>Week 1 Events</h2>
<ul><h3>
	<li>Tuesday: Tic Tac Toe Tournament</li>
	<li>Wednesday: Hangman </li>
	<li>Thursday: Paper Football Distance Competition </li>
	<li>Friday: Pictionary</li>
</ul></h3>

<br>
<h2>Week 2 Events</h2>
<ul><h3>
	<li>Monday: Heads Up</li>
</ul></h3>

<br>
<br>

</body>
</html>

grails-app/views/team/show.gsp
<%@ page import="officeolympics.Team" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'team.label', default: 'Team')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-team" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-team" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list team">
			
				<g:if test="${teamInstance?.members}">
				<li class="fieldcontain">
					<span id="members-label" class="property-label"><g:message code="team.members.label" default="Members" /></span>
					
						<g:each in="${teamInstance.members}" var="m">
						<span class="property-value" aria-labelledby="members-label"><g:link controller="teamMembers" action="show" id="${m.id}">${m?.playerName.encodeAsHTML()}</g:link></span>
						</g:each>
					
				</li>
				</g:if>
			
				<g:if test="${teamInstance?.score}">
				<li class="fieldcontain">
					<span id="score-label" class="property-label"><g:message code="team.score.label" default="Score" /></span>
					
						<span class="property-value" aria-labelledby="score-label"><g:fieldValue bean="${teamInstance}" field="score"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${teamInstance?.teamName}">
				<li class="fieldcontain">
					<span id="teamName-label" class="property-label"><g:message code="team.teamName.label" default="Team Name" /></span>
					
						<span class="property-value" aria-labelledby="teamName-label"><g:fieldValue bean="${teamInstance}" field="teamName"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:teamInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${teamInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>