grails-app/domain/officeolympics/Medals.groovy
package officeolympics

class Medals {
	String level
	String sportName
	static belongsTo = [teams: Team]
	static constraints = { teams nullable: true }
}

grails-app/controllers/officeolympics/MedalsController.groovy
package officeolympics



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class MedalsController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Medals.list(params), model:[medalsInstanceCount: Medals.count()]
    }

    def show(Medals medalsInstance) {
        respond medalsInstance
    }

    def create() {
        respond new Medals(params)
    }

    @Transactional
    def save(Medals medalsInstance) {
        if (medalsInstance == null) {
            notFound()
            return
        }

        if (medalsInstance.hasErrors()) {
            respond medalsInstance.errors, view:'create'
            return
        }

        medalsInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'medals.label', default: 'Medals'), medalsInstance.id])
                redirect medalsInstance
            }
            '*' { respond medalsInstance, [status: CREATED] }
        }
    }

    def edit(Medals medalsInstance) {
        respond medalsInstance
    }

    @Transactional
    def update(Medals medalsInstance) {
        if (medalsInstance == null) {
            notFound()
            return
        }

        if (medalsInstance.hasErrors()) {
            respond medalsInstance.errors, view:'edit'
            return
        }

        medalsInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Medals.label', default: 'Medals'), medalsInstance.id])
                redirect medalsInstance
            }
            '*'{ respond medalsInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Medals medalsInstance) {

        if (medalsInstance == null) {
            notFound()
            return
        }

        medalsInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Medals.label', default: 'Medals'), medalsInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'medals.label', default: 'Medals'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/medals/_form.gsp
<%@ page import="officeolympics.Medals" %>



<div class="fieldcontain ${hasErrors(bean: medalsInstance, field: 'teams', 'error')} ">
	<label for="teams">
		<g:message code="medals.teams.label" default="Teams" />
		
	</label>
	<g:select id="teams" name="teams.id" from="${officeolympics.Team.list()}" optionKey="id" optionValue="teamName" value="${medalsInstance?.teams?.id}" class="many-to-one" noSelection="['null': '']"/>

</div>

<div class="fieldcontain ${hasErrors(bean: medalsInstance, field: 'level', 'error')} required">
	<label for="level">
		<g:message code="medals.level.label" default="Level" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="level" required="" value="${medalsInstance?.level}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: medalsInstance, field: 'sportName', 'error')} required">
	<label for="sportName">
		<g:message code="medals.sportName.label" default="Sport Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="sportName" required="" value="${medalsInstance?.sportName}"/>

</div>

grails-app/views/medals/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'medals.label', default: 'Medals')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-medals" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-medals" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${medalsInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${medalsInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:medalsInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/medals/edit.gsp
<%@ page import="officeolympics.Medals" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'medals.label', default: 'Medals')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-medals" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-medals" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${medalsInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${medalsInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:medalsInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${medalsInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/medals/index.gsp
<%@ page import="officeolympics.Medals" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'medals.label', default: 'Medals')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-medals" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-medals" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<th><g:message code="medals.teams.label" default="Teams" /></th>
					
						<g:sortableColumn property="level" title="${message(code: 'medals.level.label', default: 'Level')}" />
					
						<g:sortableColumn property="sportName" title="${message(code: 'medals.sportName.label', default: 'Sport Name')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${medalsInstanceList}" status="i" var="medalsInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${medalsInstance.id}">${fieldValue(bean: medalsInstance, field: "teams.teamName")}</g:link></td>
					
						<td>${fieldValue(bean: medalsInstance, field: "level")}</td>
					
						<td>${fieldValue(bean: medalsInstance, field: "sportName")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${medalsInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/medals/show.gsp
<%@ page import="officeolympics.Medals" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'medals.label', default: 'Medals')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-medals" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-medals" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list medals">
			
				<g:if test="${medalsInstance?.teams}">
				<li class="fieldcontain">
					<span id="teams-label" class="property-label"><g:message code="medals.teams.label" default="Teams" /></span>
					
						<span class="property-value" aria-labelledby="teams-label"><g:link controller="team" action="show" id="${medalsInstance?.teams?.id}">${medalsInstance?.teams?.teamName.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${medalsInstance?.level}">
				<li class="fieldcontain">
					<span id="level-label" class="property-label"><g:message code="medals.level.label" default="Level" /></span>
					
						<span class="property-value" aria-labelledby="level-label"><g:fieldValue bean="${medalsInstance}" field="level"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${medalsInstance?.sportName}">
				<li class="fieldcontain">
					<span id="sportName-label" class="property-label"><g:message code="medals.sportName.label" default="Sport Name" /></span>
					
						<span class="property-value" aria-labelledby="sportName-label"><g:fieldValue bean="${medalsInstance}" field="sportName"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:medalsInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${medalsInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>