grails-app/domain/officeolympics/Result.groovy
package officeolympics

class Result {
	
		Team goldWinner
		Team silverWinner
		Team bronzeWinner
		String sportName
}

grails-app/controllers/officeolympics/ResultController.groovy
package officeolympics



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class ResultController {

	def gold;
	def silver;
	def bronze;
	def goldWinner;
	def silverWinner;
	def bronzeWinner;
    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Result.list(params), model:[resultInstanceCount: Result.count()]
    }

    def show(Result resultInstance) {
        respond resultInstance
    }

    def create() {
        respond new Result(params)
    }

    @Transactional
    def save(Result resultInstance) {
        if (resultInstance == null) {
            notFound()
            return
        }

        if (resultInstance.hasErrors()) {
            respond resultInstance.errors, view: 'create'
            return
        }

        gold = new Medals();
        gold.sportName = resultInstance.sportName;
        gold.level = "Gold";
        goldWinner = resultInstance.goldWinner
        gold.teams = goldWinner
        Team.findById(goldWinner.id).medals.add(gold)
        Team.findById(goldWinner.id).score += 3;
        gold.save flush: true

        silver = new Medals();
        silver.sportName = resultInstance.sportName;
        silver.level = "Silver";
        silverWinner = resultInstance.silverWinner
        silver.teams = silverWinner
        Team.findById(silverWinner.id).medals.add(silver)
        Team.findById(silverWinner.id).score += 2
        silver.save flush: true

        bronze = new Medals();
        bronze.sportName = resultInstance.sportName;
        bronze.level = "Bronze";
        bronzeWinner = resultInstance.bronzeWinner
        bronze.teams = bronzeWinner
        Team.findById(bronzeWinner.id).medals.add(bronze)
        Team.findById(bronzeWinner.id).score += 1
        bronze.save flush: true

        redirect(controller: 'team', view: 'index')
    }

    def edit(Result resultInstance) {
        respond resultInstance
    }

    @Transactional
    def update(Result resultInstance) {
        if (resultInstance == null) {
            notFound()
            return
        }

        if (resultInstance.hasErrors()) {
            respond resultInstance.errors, view:'edit'
            return
        }

        resultInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Result.label', default: 'Result'), resultInstance.id])
                redirect resultInstance
            }
            '*'{ respond resultInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Result resultInstance) {

        if (resultInstance == null) {
            notFound()
            return
        }

        resultInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Result.label', default: 'Result'), resultInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'result.label', default: 'Result'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/result/index.gsp
<%@ page import="officeolympics.Result" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'result.label', default: 'Result')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-result" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-result" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="bronzeWinner" title="${message(code: 'result.bronzeWinner.label', default: 'Bronze Winner')}" />
					
						<g:sortableColumn property="goldWinner" title="${message(code: 'result.goldWinner.label', default: 'Gold Winner')}" />
					
						<g:sortableColumn property="silverWinner" title="${message(code: 'result.silverWinner.label', default: 'Silver Winner')}" />
					
						<g:sortableColumn property="sportName" title="${message(code: 'result.sportName.label', default: 'Sport Name')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${resultInstanceList}" status="i" var="resultInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${resultInstance.id}">${fieldValue(bean: resultInstance, field: "bronzeWinner")}</g:link></td>
					
						<td>${fieldValue(bean: resultInstance, field: "goldWinner")}</td>
					
						<td>${fieldValue(bean: resultInstance, field: "silverWinner")}</td>
					
						<td>${fieldValue(bean: resultInstance, field: "sportName")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${resultInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>