grails-app/domain/officeolympics/TeamMembers.groovy
package officeolympics

class TeamMembers {
	String playerName
	static belongsTo = [teams: Team]
	static constraints = { teams nullable: true }
	String toString() {return playerName}
	
}

grails-app/controllers/officeolympics/TeamMembersController.groovy
package officeolympics



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class TeamMembersController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond TeamMembers.list(params), model:[teamMembersInstanceCount: TeamMembers.count()]
    }

    def show(TeamMembers teamMembersInstance) {
        respond teamMembersInstance
    }

    def create() {
        respond new TeamMembers(params)
    }

    @Transactional
    def save(TeamMembers teamMembersInstance) {
        if (teamMembersInstance == null) {
            notFound()
            return
        }

        if (teamMembersInstance.hasErrors()) {
            respond teamMembersInstance.errors, view:'create'
            return
        }

        teamMembersInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'teamMembers.label', default: 'TeamMembers'), teamMembersInstance.id])
                redirect teamMembersInstance
            }
            '*' { respond teamMembersInstance, [status: CREATED] }
        }
    }

    def edit(TeamMembers teamMembersInstance) {
        respond teamMembersInstance
    }

    @Transactional
    def update(TeamMembers teamMembersInstance) {
        if (teamMembersInstance == null) {
            notFound()
            return
        }

        if (teamMembersInstance.hasErrors()) {
            respond teamMembersInstance.errors, view:'edit'
            return
        }

        teamMembersInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'TeamMembers.label', default: 'TeamMembers'), teamMembersInstance.id])
                redirect teamMembersInstance
            }
            '*'{ respond teamMembersInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(TeamMembers teamMembersInstance) {

        if (teamMembersInstance == null) {
            notFound()
            return
        }

        teamMembersInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'TeamMembers.label', default: 'TeamMembers'), teamMembersInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'teamMembers.label', default: 'TeamMembers'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/teamMembers/_form.gsp
<%@ page import="officeolympics.TeamMembers" %>



<div class="fieldcontain ${hasErrors(bean: teamMembersInstance, field: 'teams', 'error')} ">
	<label for="teams">
		<g:message code="teamMembers.teams.label" default="Teams" />
		
	</label>
	<g:select id="teams" name="teams.id" from="${officeolympics.Team.list()}" optionKey="id" optionValue="teamName" value="${teamMembersInstance?.teams?.id}" class="many-to-one" noSelection="['null': '']"/>

</div>

<div class="fieldcontain ${hasErrors(bean: teamMembersInstance, field: 'playerName', 'error')} required">
	<label for="playerName">
		<g:message code="teamMembers.playerName.label" default="Player Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="playerName" required="" value="${teamMembersInstance?.playerName}"/>

</div>

grails-app/views/teamMembers/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'teamMembers.label', default: 'TeamMembers')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-teamMembers" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-teamMembers" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${teamMembersInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${teamMembersInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:teamMembersInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/teamMembers/edit.gsp
<%@ page import="officeolympics.TeamMembers" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'teamMembers.label', default: 'TeamMembers')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-teamMembers" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-teamMembers" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${teamMembersInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${teamMembersInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:teamMembersInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${teamMembersInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/teamMembers/index.gsp
<%@ page import="officeolympics.TeamMembers" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'teamMembers.label', default: 'TeamMembers')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-teamMembers" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-teamMembers" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<th><g:message code="teamMembers.teams.label" default="Teams" /></th>
					
						<g:sortableColumn property="playerName" title="${message(code: 'teamMembers.playerName.label', default: 'Player Name')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${teamMembersInstanceList}" status="i" var="teamMembersInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${teamMembersInstance.id}">${fieldValue(bean: teamMembersInstance, field: "teams.teamName")}</g:link></td>
					
						<td>${fieldValue(bean: teamMembersInstance, field: "playerName")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${teamMembersInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/teamMembers/show.gsp
<%@ page import="officeolympics.TeamMembers" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'teamMembers.label', default: 'TeamMembers')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-teamMembers" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-teamMembers" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list teamMembers">
			
				<g:if test="${teamMembersInstance?.teams}">
				<li class="fieldcontain">
					<span id="teams-label" class="property-label"><g:message code="teamMembers.teams.label" default="Teams" /></span>
					
						<span class="property-value" aria-labelledby="teams-label"><g:link controller="team" action="show" id="${teamMembersInstance?.teams?.id}">${teamMembersInstance?.teams?.teamName.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${teamMembersInstance?.playerName}">
				<li class="fieldcontain">
					<span id="playerName-label" class="property-label"><g:message code="teamMembers.playerName.label" default="Player Name" /></span>
					
						<span class="property-value" aria-labelledby="playerName-label"><g:fieldValue bean="${teamMembersInstance}" field="playerName"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:teamMembersInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${teamMembersInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>